wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.11
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716909362.231595
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.10.9
      5: 0.15.11
      8:
      - 5
      13: darwin-x86_64
aoi:
  desc: null
  value: BWA
buffer:
  desc: null
  value: '500'
model:
  desc: null
  value: rf
target:
  desc: null
  value: school
data_split:
  desc: null
  value: Central
